mindmap
  root(MAIN)
    System Requirements
      Project Setup
        Readme file
        Monolith structure diagram
        ER Diagram
        Github main branch protection
        GitHub Actions CI
        Maven wrapper
        JavaFX in pom.xml
      Architectural Principles
        Layered Monolith
        Clean Architecture
      Technology Stack
        Java 25 LTS + Maven + JavaFX
        SQLite + JDBC + Flyway
        GitHub Flow
        GitHub Actions
        jpackage
    Application Requirements
      MVP
        Session Context
        Login Screen
        Registration Screen
        Main Screen
        Cart Screen
        Checkout Screen
        Design
      Extra Features
        Promotions/Sale/Discounts
        Promotion Codes
        Product Search
        Product Categories
        Product Images
        Product Views
        Product Reviews
        Payment Methods
        Order History
        User Profile
      Security and Validation
        Input Validation
        Password Hashing + Salting
        Error Handling
        Immutable Data Structures
        Test Coverage